---
title: "stability selection simulation"
output: pdf_document
date: '2023-04-13'
---
```{r}
install.packages("glmnet")
```


```{r,fig.height=5, fig.width=10}
library(glmnet)
set.seed(1005780558)
n <- 115
p <- 4086
n_true_covariates <- 10
x <- matrix(rnorm(n * p), nrow = n, ncol = p)

for (i in 1:n_true_covariates) {
  corr_idx <- sample(1:p, 25)
  for (j in corr_idx) {
    x[, j] <- x[, j] + 0.95 * x[, i]
  }
} 
beta_true <- c(runif(n_true_covariates, -6, 6), rep(0, p - n_true_covariates))
index_t <- sample(1:p, n_true_covariates)
beta <- numeric(p)
beta[index_t] <- beta_true[1:n_true_covariates]
y <- x %*% beta + rnorm(n, sd = 18)
lasso_fit <- glmnet(x, y, alpha = 1)
lasso_coefs <- as.matrix(coef(lasso_fit))[-1,]

plot(0,0,xlim = c(max(log(lasso_fit$lambda)), min(log(lasso_fit$lambda))),ylim = c(min(lasso_coefs), max(lasso_coefs)),type = 'n', ylab = 'Coefficient', xlab = 'log(lambda)')

for (i in 1:nrow(lasso_coefs)) {
  line_col <- 'grey50'
  if (i %in% index_t) {
    line_col <- 'red'
  }
  
  line_size <- 1
  if (i %in% index_t) {
    line_size <- 2
  }
  
  line_y <- c(0, lasso_coefs[i,])
  lambda_with_zero <- c(max(log(lasso_fit$lambda)),log(lasso_fit$lambda))
  
  lines(lambda_with_zero, line_y, col = line_col, lwd = line_size)
}

title('LASSO')
legend("topright", legend=c("Signal variables", "Noise variables"), col=c("red", "grey75"), lwd=c(2, 1))

```



```{r,fig.height=5, fig.width=5}
stability_selection <- function(x, y, alpha, q = 4000, index_t) {
  n <- nrow(x)
  p <- ncol(x)
  
  lambdas <- glmnet(x, y, alpha = 1, nlambda = 100)$lambda
  selected <- matrix(0, nrow = p, ncol = length(lambdas))
  
  for (i in 1:q) {
    new <- apply(x, 2, function(x) x + runif(n, alpha, 1))
    idx <- sample(n)
    idx1 <- idx[1:(n/2)]
    idx2 <- idx[-(1:(n/2))]
    mod1 <- glmnet(new[idx1,], y[idx1], alpha = 1, lambda = lambdas)
    coef1 <- as.matrix(coef(mod1))
    nonzero1 <- abs(sign(coef1))[-1,]
    mod2 <- glmnet(new[idx2,], y[idx2], alpha = 1, lambda = lambdas)
    coef2 <- as.matrix(coef(mod2))
    nonzero2 <- abs(sign(coef2))[-1,]
    selected <- selected + nonzero1 + nonzero2
  }
  
  ratio_lambda <- apply(selected, 2, function(x) x/(q*2))
  result <- list(ratio_lambda = ratio_lambda,lambdas = lambdas, n = n, p = p, index_t = index_t)
  structure(result, class = 'stab')
}
plot.stab <- function(object) {
  plot(
    x = -object$lambdas, 
    y = rep(NA, length(object$lambdas)), 
    type='n', ylab = 'ratio', xlab = '-lambda',
    ylim = c(min(object$ratio_lambda), max(object$ratio_lambda))
  )
  
  for (i in 1:object$p) {
    line_col <- 'grey75'
    if (i %in% object$index_t) line_col <- 'red'
    
    line_size <- 1
    if (i %in% object$index_t) line_size <- 2
    
    line_y <- object$ratio_lambda[i,]
    line_y[which.min(line_y)] <- 0
    
    lines(-object$lambdas, line_y, col = line_col, lwd = line_size)
  }
}
selection <- stability_selection(x, y, 0.01, 4000, index_t)
plot(selection)
title('Stability Selection')
legend("topright", legend=c("Signal variables", "Noise variables"), col=c("red", "grey75"), lwd=c(2, 1))

```













